server:
  servlet:
    context-path: /api
spring:
  datasource:
    password: ''
    url: jdbc:postgresql://localhost:26257/postgres
    username: root
    initialization-mode: always
  devtools:
    add-properties: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
